name: Scheduler

on:
  schedule:
    - cron: '35 12 * * *'  # Runs every day at 12:35 PM UTC

jobs:
  Scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test file
        run: echo hello > test.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: test.txt

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: my-artifact
